name: Run Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use Python 3.9 or adjust according to your project's needs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Set up Django environment
      run: |
        python manage.py makemigrations
        python manage.py migrate  # Apply migrations

    - name: Run Django tests
      env:
        DJANGO_SETTINGS_MODULE: your_project.settings  # Replace with your actual settings module
      run: |
        python manage.py test  # Run the Django test suite
